web:
    build: ./containers/web
    volumes:
        - ./code:/app
    ports:
        - "80:80"
    links:
        - db:db
db:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=demoapp
    volumes:
        - ./containers/db:/etc/mysql/conf.d
